ALTER TABLE article
    ALTER COLUMN article_text TYPE character varying(5000);


INSERT INTO article (article_id, article_text, article_title) VALUES
('1', 'Interesting facts about UzbekistanLocated in the heart of the Central Asia, the Republic of Uzbekistan is famous for its numerous architectural monuments, incredible natural landscapes, magnificent palaces, and ruins of fortresses of past civilizations, outstanding cultural events, gastronomic delights and famous craft workshops. From the first visit, our country evokes extraordinary feelings that prompt us to come here repeatedly.The Republic of Uzbekistan includes 12 regions and the autonomous Republic of Karakalpakstan.Each corner of Uzbekistan attracts with its features. In Tashkent, you can take a walk in the most beautiful metro in the world or see the most ancient manuscript – the Koran of Usman', 'Uzbekistan'),
('2', 'Sweden has a number of World Heritage Sites, which are popular as tourist destinations. These include: The agricultural landscape of the island of Öland, visited for its geological and geographical features, Birka and Hovgården on the islands Björkö and Adelsö in Mälaren near Stockholm, The church village of Gammelstad, Luleå, in northern Sweden ,Drottningholm Palace, Theatre, and the royal domain, Engelsberg Ironworks and Laponian area. Due to Sweden''s northern location, the summer sun sets for only short periods of time. This phenomenon allows outdoor activities later in the evening than usual.
Sweden has a large number of lakes and forests; the former are popular for fishing and canoeing. There are several large lakes, including lake Vättern.
', 'Sweden'),
('3', 'Japan attracted 31.88 million international tourists in 2019. Japan has 21 World Heritage Sites, including Himeji Castle, Historic Monuments of Ancient Kyoto and Nara. Popular foreign attractions include Tokyo and Hiroshima, Mount Fuji, ski resorts such as Niseko in Hokkaido, Okinawa, riding the shinkansen and taking advantage of Japan''s hotel and hotspring network.
The 2017 Travel and Tourism Competitiveness Report ranked Japan 4th out of 141 countries overall, which was the highest in Asia. Japan gained relatively high scores in almost all of the featured aspects, such as health and hygiene, safety and security, cultural resources and business travel.
', 'Japan'),
('4', 'France is visited by 90 million foreign tourists yearly. It is the most visited country in the world. France has 45 sites inscribed in the UNESCO''s World Heritage List and features cities or sites of high cultural interest, beaches and seaside resorts, ski resorts, as well as rural regions that many enjoy for their beauty and tranquility. Small and picturesque French villages of quality heritage are promoted through the association Les Plus Beaux Villages de France. The "Remarkable Gardens" label is a list of the over two hundred gardens classified by the Ministry of Culture. This label is intended to protect and promote remarkable gardens and parks' , 'France'),
('5', 'Tourism is an economic contributor to the Kingdom of Thailand. Tourism worldwide in 2017 accounted for 10.4% of global GDP and 313 million jobs, or 9.9% of total employment. Most governments view tourism as an easy moneymaker and a shortcut to economic development. Tourism success is measured by the number of visitors. Prior to the pandemic, Thailand was the world''s eighth most visited country as per World Tourism rankings compiled by the United Nations World Tourism Organization. In 2019, Thailand received 39.8 million international tourists, ahead of the United Kingdom and Germany and received fourth highest international tourism earning at 60.5 billion US dollar.', 'Thailand'),
('6', 'Greece has been a major tourist destination and attraction in Europe since the 1970s for its rich culture and history, which is reflected in large part by its 18 UNESCO World Heritage Sites, among the most in Europe and the world[ as well as for its long coastline, many islands, and beaches. The Egremnoi sand beach in the Greek island of Lefkada, noted for its blue crystal waters, is a popular tourist destination. Some of the country''s major tourist destinations include the capital city Athens, the islands of Santorini, Mykonos, Rhodes, Corfu and Crete, as well as the peninsula of Chalkidice.
', 'Greece'),
('7','Specks of emerald green enveloped by dazzling turquoise waters like scattered beads in the ocean; white powdery beaches, tall palms lean on towards the sea, crystalline white sands giving way to crystal clear waters, shades of turquoise blend flawlessly with deeper hues of blue; pristine coral reefs and some of the most incredible underwater life on our planet.
Rising from the deep blue of the vast expanse of the Indian Ocean are more than a thousand islands and thousands more reefs that form the Maldives. What better place to relax and enjoy yourself than the romantic dunes that adorn these islands.
', 'Maldives'),
('8','One of the oldest civilisations in the world, India is a mosaic of multicultural experiences. With a rich heritage and myriad attractions, the country is among the most popular tourist destinations in the world. It covers an area of 32, 87,263 sq. km. As the 7th largest country in the world, India stands apart from the rest of Asia, marked off as it is by mountains and the sea, which give the country a distinct geographical entity. Fringed by the Great Himalayas in the north, it stretches southwards and at the Tropic of Cancer and the Arabian Sea on the west.', 'India'),
('9','In the United States, tourism is a large industry that serves millions of international and domestic tourists yearly. Foreigners visit the U.S. to see natural wonders, cities, historic landmarks, and entertainment venues. Americans seek similar attractions, as well as recreation and vacation areas. Tourism in the United States grew rapidly in the form of urban tourism during the late nineteenth and early twentieth centuries. By the 1850s, tourism in the United States was well established both as a cultural activity and as an industry. New York City, Los Angeles, Chicago, Boston, all major U.S. cities, have attracted numerous tourists since the 1890s.', 'USA'),
('10','Iceland is typically divided into seven different geographical regions, including the Reykjavík capital area. Each region differs slightly with respect to both culture and landscape, but all are uniquely Icelandic.  Iceland is well known for its untouched nature and unique atmosphere. Iceland receives the highest number of tourists during summer . Iceland''s largest tourism markets comprises tourists from Central/South Europe, followed by those from other regions: North America, the UK, then the Nordic countries. In terms of visitors from individual countries, the top five countries are the UK, USA, Germany, France and Norway. Canada had the largest percentage increase in visitor numbers in recent years.', 'Iceland'),
('11','The United Arab Emirates is a country in Western Asia. It is located at the eastern end of the Arabian Peninsula. Abu Dhabi is the nation''s capital, while Dubai, the most populous city, is an international hub. The United Arab Emirates is an elective monarchy formed from a federation of seven emirates, consisting of Abu Dhabi , Ajman, Dubai, Fujairah, Ras Al Khaimah, Sharjah and Umm Al Quwain.  Each emirate is governed by an emir and together the emirs form the Federal Supreme Council. The members of the Federal Supreme Council elect a president and vice president from among their members.  The  most famous city is Dubai.', 'United Arab Emirates'),
('12','Tourism in Turkey is focused largely on a variety of historical sites, and on seaside resorts along its Aegean and Mediterranean Sea coasts. Turkey has also become a popular destination for culture, spa, and health care. At its height in 2020, Turkey attracted around 51 million foreign tourists, ranking as the sixth-most-popular tourist destination in the world. The total number fluctuated between around 41 million in 2015, and around 30 million in 2016. However, with the number of foreign visitors increasing to 37.9 million, to 46.1 million visitors. Istanbul is one of the most important tourism spots not only in Turkey but also in the world', 'Turkey')


